name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**/.tsx?'
      - '.storybook/**'

jobs:
  storybook:
    name: Build & deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build

      - name: Build Storybook
        run: yarn storybook:build

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: docs-build # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs # The folder that we serve our Storybook files from
